/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pet.management.service;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PetServiceTest {
    @Test void appHasAGreeting() {
        PetService classUnderTest = new PetService();
        assertNotNull(classUnderTest, "PetService should have a greeting");
    }
}
